#' Create a graph that describes network of package functions
#'
#' Create a DiagrammeR graph that contains nodes of
#' the type \code{function} and edges that have the
#' relationship \code{called_in}.
#' @param pkg_fcn_info a tibble object that contains
#' package function information. This is created by the
#' \code{get_pkg_fcn_info()} function.
#' @param pkg_name an optional package name for filtering
#' the tibble provided to \code{pkg_fcn_info}, which is
#' useful if that tibble describes multiple packages.
#' @importFrom dplyr filter select rename mutate
#' @importFrom tidyr unnest
#' @importFrom DiagrammeR create_graph add_nodes_from_table
#' @importFrom DiagrammeR add_edges_from_table rescale_node_attrs
#' @export
create_function_graph <- function(pkg_fcn_info,
                                  pkg_name = NULL) {

  if (!is.null(pkg_name)) {

    pkg_fcn_info <-
      pkg_fcn_info %>%
      dplyr::filter(pkg_name == pkg_name)
  }

  edge_tbl <-
    pkg_fcn_info %>% tidyr::unnest(pkg_fcns_called) %>%
    dplyr::select(fcn_name, pkg_fcns_called) %>%
    dplyr::rename(from = pkg_fcns_called) %>%
    dplyr::rename(to = fcn_name) %>%
    dplyr::mutate(color = "gray90") %>%
    dplyr::mutate(arrowhead = "dot")

  node_tbl <-
    pkg_fcn_info %>%
    dplyr::mutate(tooltip = paste0("file: ", r_file)) %>%
    dplyr::select(fcn_name, exported, n_pkg_fcns_called, tooltip) %>%
    dplyr::mutate(fillcolor = ifelse(exported, "green", "lightblue")) %>%
    dplyr::mutate(fontcolor = "gray35") %>%
    dplyr::mutate(color = "gray90")

  graph <-
    DiagrammeR::create_graph() %>%
    DiagrammeR::add_nodes_from_table(
      table = node_tbl,
      label_col = fcn_name,
      set_type = "function") %>%
    DiagrammeR::add_edges_from_table(
      table = edge_tbl,
      from_col = from,
      to_col = to,
      from_to_map = label,
      set_rel = "called_in") %>%
    DiagrammeR::rescale_node_attrs(
      node_attr_from = n_pkg_fcns_called,
      to_lower_bound = 0.15,
      to_upper_bound = 1.00,
      node_attr_to = width)

  graph
}

#' Show all package functions that are called from a given function
#'
#' Create a DiagrammeR graph that contains nodes of
#' the type \code{function} and edges that have the
#' relationship \code{called_in}.
#' @param fcn_graph a function network graph generated by the
#' \code{create_function_graph()} function.
#' @param caller_fcn the name of the function that is
#' to examined for its calls of package functions.
#' @importFrom DiagrammeR select_nodes trav_in transform_to_subgraph_ws render_graph
#' @export
show_called_functions <- function(fcn_graph, caller_fcn) {

  suppressMessages(
    fcn_graph %>%
      DiagrammeR::select_nodes(label == caller_fcn) %>%
      DiagrammeR::trav_in(add_to_selection = TRUE) %>%
      DiagrammeR::transform_to_subgraph_ws() %>%
      DiagrammeR::render_graph(layout = "nicely")
  )
}
